// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "CompressorSubsystem.h"
#include "../RobotMap.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES


CompressorSubsystem::CompressorSubsystem(int channel) : Subsystem("PneumaticSubsystem") {
	printf("Compressor Subsystem Constructor called.\n");
	workingCompressor = new Compressor(7);
    workingCompressor->SetClosedLoopControl(true);
    // on the testBot, keep the compressor off until we need it
    if (!RobotMap::testBot) workingCompressor->Start();
    else workingCompressor->Stop();
}

void CompressorSubsystem::InitDefaultCommand() {
}

void CompressorSubsystem::Toggle() {
	bool newstate = !workingCompressor->Enabled();
	if (newstate) workingCompressor->Start();
	else workingCompressor->Stop();
	printf("Compressor toggled to %s\n", newstate ? "on" : "off");
}

void CompressorSubsystem::TurnOn() {
	workingCompressor->Start();
	printf("Compressor on\n");
}

void CompressorSubsystem::TurnOff() {
	workingCompressor->Stop();
	printf("Compressor off\n");
}


