// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef DRIVESUBSYSTEM_H
#define DRIVESUBSYSTEM_H

#include "WPILib.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class DriveSubsystem: public Subsystem {
private:
	// It's desirable that everything possible under private except
	// for methods that implement subsystem capabilities
public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	CANTalon* lFront;
	CANTalon* lBack;
	CANTalon* rFront;
	CANTalon* rBack;
	RobotDrive* robotDrive;
	CANTalon* backLeftMotor;
	CANTalon* backRightMotor;
	Encoder* lEncoder;
	Encoder* rEncoder;
	double previousClosedLoopError;	// sum of left & right
	int numberofsame;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	DriveSubsystem();
	void SetPIDDistance( double left, double right);
	void DriveJoysticks(double y, double x);
	void InitDefaultCommand();
	double GetLeftEncoderPosition();
	double GetRightEncoderPosition();
	double LeftTalonGet();
	double RightTalonGet();
	double GetLeftSpeed(); // return value in inches/sec
	double GetRightSpeed(); // return value in inches/sec
	bool IsFinished();
//	float distanceSensorThreshold = 0.7;
};

#endif
