// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.




#include "DriveSubsystem.h"
#include "../RobotMap.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "../Commands/DriveCommand.h"
#include "Parameters.h"
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

DriveSubsystem::DriveSubsystem() : Subsystem("DriveSubsystem") {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	lFront = RobotMap::driveFrontLeft;
	rFront = RobotMap::driveFrontRight;
	robotDrive = RobotMap::driveSubsystem;
	backLeftMotor = RobotMap::driveBackLeft;
	backRightMotor = RobotMap::driveBackRight;

	RobotMap::driveBackLeft->ClearError();
	RobotMap::driveBackLeft->SetPosition(0.0);
	RobotMap::driveBackLeft->SetFeedbackDevice(CANTalon::QuadEncoder);
	if (RobotMap::testBot) RobotMap::driveBackLeft->SetSensorDirection(true);

	RobotMap::driveBackRight->SetPosition(0.0);
	RobotMap::driveBackRight->SetFeedbackDevice(CANTalon::QuadEncoder);
	if (RobotMap::testBot) RobotMap::driveBackRight->SetSensorDirection(true);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
}
    
void DriveSubsystem::SetPIDDistance(double left, double right)
{
	double leftPosition = GetLeftEncoderPosition();
	double rightPosition = GetRightEncoderPosition();

	// Test bot right encoder counts 1.405 ticks for every left encoder tick
	if (RobotMap::testBot) right *= -1.405;

	// account for left drive being reversed, on production bot only??
	if (!RobotMap::testBot) left = leftPosition - left;
	else left += leftPosition;
	right += rightPosition;

	RobotMap::driveBackLeft->SetControlMode(CANSpeedController::kPosition);
	RobotMap::driveBackLeft->SetPID(Parameters::driveP,Parameters::driveI,
									Parameters::driveD,Parameters::driveF);
	RobotMap::driveBackLeft->SetIzone(Parameters::driveIZone);
	RobotMap::driveBackLeft->SetCloseLoopRampRate(Parameters::driveIZone);
	RobotMap::driveBackLeft->ClearIaccum();

	printf("PID Left from=%1.0f, to=%1.2f, driveP=%1.3f, driveI=%1.3f, driveD=%1.3f, driveF=%1.3f.\n",
			leftPosition, left, Parameters::driveP, Parameters::driveI, Parameters::driveD, Parameters::driveF);

	RobotMap::driveBackRight->SetControlMode(CANSpeedController::kPosition);
	RobotMap::driveBackRight->SetPID(Parameters::driveP,Parameters::driveI,
									 Parameters::driveD,Parameters::driveF);
	RobotMap::driveBackRight->SetIzone(Parameters::driveIZone);
	RobotMap::driveBackRight->SetCloseLoopRampRate(Parameters::driveIZone);
	RobotMap::driveBackRight->ClearIaccum();

	printf("PID Right from=%1.0f, to=%1.2f, driveP=%1.3f, driveI=%1.3f, driveD=%1.3f, driveF=%1.3f.\n",
			rightPosition, right, Parameters::driveP, Parameters::driveI, Parameters::driveD, Parameters::driveF);

	RobotMap::driveBackLeft->Set(left);
	RobotMap::driveBackRight->Set(right);

}

void DriveSubsystem::DriveJoysticks(double y, double x)
{
	robotDrive->ArcadeDrive(y,x);
}

void DriveSubsystem::InitDefaultCommand() {
	SetDefaultCommand(Robot::driveCommand);
}

double DriveSubsystem::GetLeftEncoderPosition() {
	return ((CANTalon*) backLeftMotor)->GetPosition();
}

double DriveSubsystem::GetRightEncoderPosition() {
	return ((CANTalon*) backRightMotor)->GetPosition();
}

double DriveSubsystem::LeftTalonGet() {
	return ((CANTalon*) backLeftMotor)->Get();
}

double DriveSubsystem::RightTalonGet() {
	return ((CANTalon*) backRightMotor)->Get();
}


