// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.




#include "PickupSubsystem.h"

//comment #include "../Commands/PickupDriveCommand.h"
#include "../RobotMap.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

PickupSubsystem::PickupSubsystem() : Subsystem("PickupSubsystem") {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	pickupMotor1 = RobotMap::pickupMotor1;
	pickupMotor2 = RobotMap::pickupMotor2;
	pickupEncoder = RobotMap::pickupSubsystempickupEncoder;
	armFlapSolenoid = RobotMap::armFlapSolenoid;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
}
    
void PickupSubsystem::InitDefaultCommand() {
	// Set the default command for a subsystem here.
	//SetDefaultCommand(new MySpecialCommand());
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	//comment SetDefaultCommand(new PickupDriveCommand());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}


// Put methods for controlling this subsystem
// here. Call these from Commands.

void PickupSubsystem::ArmFlapUp() {
	armFlapSolenoid->Set(DoubleSolenoid::kForward);
}

void PickupSubsystem::ArmFlapDown() {
	armFlapSolenoid->Set(DoubleSolenoid::kReverse);
}

