// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "AutonomousCommand3Tote1Can.h"




AutonomousCommand3Tote1Can::AutonomousCommand3Tote1Can() {
	Command* PickUpTote = new AutoLiftCommand(50);
	Command* GoDownTote = new AutoLiftCommand(-50);
	Command* MoveHalfForward = new AutoForwardCommand(50);
	AddSequential(new AutoLiftCommand(100));
	AddParallel(new AutoForwardCommand(5));
	AddSequential(new AutoForwardCommand(5));
	AddSequential(new AutoLiftCommand(-100));
	AddSequential(PickUpTote);
	AddParallel(MoveHalfForward);
	AddSequential(MoveHalfForward);
	AddParallel(GoDownTote);
	AddSequential(PickUpTote);
	AddParallel(MoveHalfForward);
	AddSequential(MoveHalfForward);
	AddParallel(GoDownTote);
	AddSequential(PickUpTote);
	AddSequential(new Turn90Command(true));
	AddSequential(new AutoForwardCommand(10000));
}
