// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
#include "AutonomousCommand1Can.h"
AutonomousCommand1Can::AutonomousCommand1Can() {
	// Need to go up twice to get a can
AddSequential(Robot::oi->toteUp);
AddSequential(Robot::oi->toteUp);
// TODO: DrivePID only goes straight right now. We need to be able to pass in values
// but I want to coordinate with Charles
AddSequential(Robot::oi->drivePID);
// And now drive into Auto Zone
// TODO: Need to pass in distance. Both sides should be the same
AddSequential(Robot::oi->drivePID);
}
