// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "AutonomousCommand1Tote1Can.h"

AutonomousCommand1Tote1Can::AutonomousCommand1Tote1Can() {
	AddSequential(new AutoLiftCommand(100));
	AddParallel(new AutoForwardCommand(5));
	AddSequential(new AutoForwardCommand(5));
	AddSequential(new AutoLiftCommand(-100));
	AddSequential(new AutoLiftCommand(50));
	AddSequential(new Turn90Command(true));
	AddSequential(new AutoForwardCommand(10000));
}
