/*
 * DriveDistanceCommand.h
 *
 *  Created on: Jan 29, 2015
 *      Author: Ligerbots
 */

#ifndef SRC_COMMANDS_DRIVEDISTANCECOMMAND_H_
#define SRC_COMMANDS_DRIVEDISTANCECOMMAND_H_





#endif /* SRC_COMMANDS_DRIVEDISTANCECOMMAND_H_ */
// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef DRIVEDISTANCECOMMAND_H
#define DRIVEDISTANCECOMMAND_H



#include "../Robot.h"
#include "DriveCommand.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class DriveDistance: public Command {
private:
	double _distL;
	double _distR;
	bool isCommandDone = false;
	double remainingDistance = 0.0;
	// maxDecelDisatnce is the distance travelled while decelerating at the
	// maximum rate based on rateStep
	double maxDecelDistance = 0.0;
	double rateLeft = 0.0;
	double rateRight = 0.0;
	double maxRate = 0.6;
	// Make sure to disable the VoltageRampRate on the drive Talons
	// Use this to step up the voltage for acceleration and deceleration
	// Using the Talon VoltageRampRate interferes with this control loop
	double rateStep = .02;
	double initialRate = 0.15; 	// overcome intertia
	// If we're off by 1 inch, this is how much we increase the right side voltage
	double rateScale = 0.04;
	// timeToStop is how long it takes to get to 0 volts from current rate at rateStep per cycle
	double timeToStop = 0.0;

	int timeTicks = 0;
	double encoderStartL, encoderStartR;
	DriveSubsystem *driveSubsystem;

public:
	DriveDistance(double distL, double distR);
	virtual void Initialize();
	virtual void Execute();
	virtual bool IsFinished();
	virtual void End();
	virtual void Interrupted();
	double distanceTravelledL;
	double distanceTravelledR;
};

#endif
