/*
 * DriveDistanceCommand.h
 *
 *  Created on: Jan 29, 2015
 *      Author: Ligerbots
 */

#ifndef SRC_COMMANDS_DRIVEDISTANCECOMMAND_H_
#define SRC_COMMANDS_DRIVEDISTANCECOMMAND_H_





#endif /* SRC_COMMANDS_DRIVEDISTANCECOMMAND_H_ */
// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef DRIVEDISTANCECOMMAND_H
#define DRIVEDISTANCECOMMAND_H


#include "Commands/Subsystem.h"
#include "../Robot.h"
#include "DriveCommand.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class DriveDistanceCommand: public Command {
private:
	int distance;
	bool isCommandDone;
	float prevLeftEnc,prevRightEnc;
	float distanceTraveled;
public:
	DriveDistanceCommand(int dist);
	virtual void Initialize();
	virtual void Execute();
	virtual bool IsFinished();
	virtual void End();
	virtual void Interrupted();
};

#endif
