// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#pragma once


#include "Commands/Subsystem.h"
//TODO #includes
#include "../Robot.h"
#include "PositionElevator.h"
#include "DriveDistanceCommand.h"
#include "DriveCommand.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class OneToteAndCanAuto: public CommandGroup {
public:
	OneToteAndCanAuto();
private:
	Command* GoUpTote();
	Command* turn90();
	Command* DriveToCenter();
};
