// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "PushTote.h"

PushTote::PushTote() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::totePusher);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}

// Called just before this Command runs the first time
void PushTote::Initialize() {
	count = 0;
	limit = 41;
}

// Called repeatedly when this Command is scheduled to run
void PushTote::Execute() {
	if (count == 0) {
		Robot::totePusher->ExtendPusher();
	}
	else if (count <= limit) {
		printf("totePusher extend");
	}
	else {
		Robot::totePusher->RetractPusher();
		finish = true;
	}
	count++;
}

// Make this return true when this Command no longer needs to run execute()
bool PushTote::IsFinished() {
	return finish;
}

// Called once after isFinished returns true
void PushTote::End() {
	printf("totePusher retracted");
	finish = false;
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void PushTote::Interrupted() {

}
