// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef PUSHTOTE_H
#define PUSHTOTE_H



#include "../Robot.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class PushTote: public Command {
public:
	PushTote();
	virtual void Initialize();
	virtual void Execute();
	virtual bool IsFinished();
	virtual void End();
	virtual void Interrupted();

private:
	int count = 0;
	bool finish = false;
	int limit = 25;
};

#endif
