// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "../Subsystems/camera.h"
#include "SwitchCamera.h"

SwitchCamera::SwitchCamera() {

}

// Called just before this Command runs the first time
void SwitchCamera::Initialize() {
	Camera::SwitchCamera();	// just get next in sequence
	printf("ToggleCamera command called \n");
}

// Called repeatedly when this Command is scheduled to run
void SwitchCamera::Execute() {
}

// Make this return true when this Command no longer needs to run execute()
bool SwitchCamera::IsFinished() {
	return true;
}

// Called once after isFinished returns true
void SwitchCamera::End() {
	
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void SwitchCamera::Interrupted() {

}
