// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "../Subsystems/Camera.h"
#include "SwitchCamera.h"

SwitchCamera::SwitchCamera() : 	_disable(false) {
}

SwitchCamera::SwitchCamera(bool disable) : _disable(disable) {
}


// Called just before this Command runs the first time
void SwitchCamera::Initialize() {
	if (!_disable) {
		// we're the switch command
		char *cam1 = Camera::GetName();
		char *camModel1 = Camera::GetModel();
		Camera::SwitchCamera();	// just get next in sequence
		char *cam2 = Camera::GetName();
		char *camModel2 = Camera::GetModel();
		printf("Camera: switching from %s (%s) to %s (%s)\n",
				cam1, camModel1,
				cam2, camModel2);
	}
	else {
		// we're the toggle cameras (disable/enable) command
		if (Camera::IsEnabled()) {
			printf("Disabling camaeras.\n");
			Camera::DisableCameras();
		}
		else {
			printf("Enabling camaeras.\n");
			Camera::EnableCameras();
		}
	}
}

// Called repeatedly when this Command is scheduled to run
void SwitchCamera::Execute() {
}

// Make this return true when this Command no longer needs to run execute()
bool SwitchCamera::IsFinished() {
	return true;
}

// Called once after isFinished returns true
void SwitchCamera::End() {
	
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void SwitchCamera::Interrupted() {

}
