// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "ToggleOverlay.h"
#include "../Subsystems/Camera.h"

ToggleOverlay::ToggleOverlay() {
}

// Called just before this Command runs the first time
void ToggleOverlay::Initialize() {
	Camera::ToggleOverlay();
}

// Called repeatedly when this Command is scheduled to run
void ToggleOverlay::Execute() {
}

// Make this return true when this Command no longer needs to run execute()
bool ToggleOverlay::IsFinished() {
	return true;
}

// Called once after isFinished returns true
void ToggleOverlay::End() {
	
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void ToggleOverlay::Interrupted() {

}
