// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#pragma once

#include "WPILib.h"

class OI {
private:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	Command* driveDistanceCommand;
	Command* applyBreakCommand;
	Command* goDownCommand;
	Command* pickupCanCommand;
	Command* pickupToteCommand;
	Command* driveCommand;
	Command* autonomousCommand;
	Command* toggleArmFlap;
	JoystickButton* joystickButton5;
	JoystickButton* joystickButton4;
	JoystickButton* joystickButton3;
	JoystickButton* joystickButton2;
	JoystickButton* joystickButton1;
	JoystickButton* toggleArmFlapButton;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
public:
	Joystick* joystick2;
	Joystick* joystick1;
	OI();
 
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES

	Joystick* getJoystick1();
	Joystick* getJoystick2();

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES
};

